spring:
  application:
    name: databaseservice
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
#    properties:
#      hibernate:
#        generate_statistics: true
#        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
#  sql:
#    init:
#      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://eurekaservice:8761/eureka/

server:
  port: 8989

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always