spring:
  application:
    name: server-registry-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: 0.0.0.0
    preferIpAddress: true
  client:
    fetch-registry: false
    register-with-eureka: false
    registryFetchIntervalSeconds: 5
